// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfGeBodLwsvuVl9bKnKfMLohDr_5PvIhM',
    appId: '1:1009897576221:android:bdce0fa8c4b03f4977b3f4',
    messagingSenderId: '1009897576221',
    projectId: 'e-price-13564',
    storageBucket: 'e-price-13564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4mzJSoJX5HC2xIgH-VtplnTakZklOhk',
    appId: '1:1009897576221:ios:62b5c67ae2c0d39777b3f4',
    messagingSenderId: '1009897576221',
    projectId: 'e-price-13564',
    storageBucket: 'e-price-13564.appspot.com',
    androidClientId: '1009897576221-98hajug3jvd1ikpptc0qusrvsruj1vqs.apps.googleusercontent.com',
    iosClientId: '1009897576221-8klso8240d3qf43b0onqu945qo51l7no.apps.googleusercontent.com',
    iosBundleId: 'com.example.ePrice',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSeRFY9p4sPO1gOa-RYSPd2IYyK0iqWkU',
    appId: '1:1009897576221:web:35f8d1f6c83036d577b3f4',
    messagingSenderId: '1009897576221',
    projectId: 'e-price-13564',
    authDomain: 'e-price-13564.firebaseapp.com',
    storageBucket: 'e-price-13564.appspot.com',
    measurementId: 'G-J6XLY531ML',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSeRFY9p4sPO1gOa-RYSPd2IYyK0iqWkU',
    appId: '1:1009897576221:web:daae736a0a4e7c1f77b3f4',
    messagingSenderId: '1009897576221',
    projectId: 'e-price-13564',
    authDomain: 'e-price-13564.firebaseapp.com',
    storageBucket: 'e-price-13564.appspot.com',
    measurementId: 'G-TER73H6VDT',
  );

}